version: "3.7"
services:
  roach1:
    container_name: roach1
    image: cockroachdb/cockroach:latest
    hostname: roach1
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start --insecure --join=roach1,roach2,roach3
    networks:
      - roachnet
    volumes:
      - roach1:/cockroach/cockroach-data
  roach2:
    container_name: roach2
    image: cockroachdb/cockroach:latest
    hostname: roach2
    command: start --insecure --join=roach1,roach2,roach3
    networks:
      - roachnet
    volumes:
      - roach2:/cockroach/cockroach-data
  roach3:
    container_name: roach3
    image: cockroachdb/cockroach:latest
    hostname: roach3
    command: start --insecure --join=roach1,roach2,roach3
    networks:
      - roachnet
    volumes:
      - roach3:/cockroach/cockroach-data
networks:
  roachnet:
    driver: bridge
volumes:
    roach1:
    roach2:
    roach3:
